VPATH = \
../challenge_1_convert_hex_to_base64 \
../challenge_2_fixed_xor \
../challenge_3_single_byte_xor_cipher

SRCS = \
test_implement_repeating_key_xor_cipher.cpp \
encode_hex_streambuf.cpp \
encode_hex.cpp \
xor_combine.cpp \
decode_hex.cpp \
repeating_stringstream.cpp

test_implement_repeating_key_xor_cipher : $(SRCS:.cpp=.o)

include ../../common_settings.mk
