VPATH = ../challenge_2_fixed_xor

SRCS = \
test_implement_repeating_key_xor_cipher.cpp \
encode_hex.cpp \
repeating_stringstream.cpp

test_implement_repeating_key_xor_cipher : $(SRCS:.cpp=.o)

include ../../common_settings.mk
