# https://bettercodehub.com/docs/configuration-manual
component_depth: 2

languages:
- name: cpp
  production:
    exclude:
      - .*/test_.*\.cpp
  test:
    include:
      - .*/test_.*\.cpp
- script
