# https://lgtm.com/docs/lgtm/lgtm.yml-configuration-file
path_classifiers:
    test:
        - "*/*/test_*.cpp"
    docs:
        - README.md
        - LICENSE.txt
    library:
        - boost
        - cryptopp
        - googletest
        - hunspell
        - openssl

extraction:
    cpp:
        prepare:
            packages:
                - g++
        after_prepare:
            - export GIT=true
            - export BOOST_DIR=$LGTM_SRC/boost
            - export GTEST_DIR=$LGTM_SRC/googletest
            - export HUNSPELL_DIR=$LGTM_SRC/hunspell
            - export CRYPTOPP_DIR=$LGTM_SRC/cryptopp
            - export OPENSSL_DIR=$LGTM_SRC/openssl
        configure:
            command:
                - ./prepare_deps
        index:
            build_command:
                - make -k
