#!/bin/bash -x

# Prerequisites:
# - Changed to relevant directory for downloading and building dependencies.
# - Latest GCC ('gcc' and 'g++') available in PATH.
# - Relatively modern Git (with support for submodules) available in PATH.
# - Caller will export BOOST_DIR, GTEST_DIR, HUNSPELL_DIR and CRYPTOPP_DIR.
# - Environment variables:
#   - GNU_MAKE: Executable name of GNU Make (at least v4.1).

function build_boost {
    # The Travis Cache plugin creates the directories beforehand, so we can't
    # use [[ ! -d $dir ]] here
    if [[ ! -x boost/bootstrap.sh ]]
    then
        git clone https://github.com/boostorg/boost.git
    fi
    pushd boost
    git pull --prune
    git submodule update --init --recursive
    ./bootstrap.sh
    ./b2 headers
    ./b2 --layout=system variant=release -j 2 --with-system
}

function build_gtest {
    if [[ ! -f googletest/googletest/make/Makefile &&
          ! -f googletest/googletest/make/GNUmakefile ]]
    then
        git clone https://github.com/google/googletest.git
    fi
    pushd googletest
    git pull --prune
    git submodule update --init --recursive
    pushd googletest/make
    $GNU_MAKE -kj 2
}

function build_hunspell {
    if [[ ! -f hunspell/configure.ac ]]
    then
        git clone https://github.com/hunspell/hunspell.git
    fi
    pushd hunspell
    git pull --prune
    git submodule update --init --recursive
    export LDFLAGS=-L/usr/local/opt/gettext/lib
    export CPPFLAGS=-I/usr/local/opt/gettext/include
    autoreconf -vfi
    ./configure
    $GNU_MAKE -kj 2
}

function build_cryptopp {
    if [[ ! -f cryptopp/GNUmakefile ]]
    then
        git clone https://github.com/weidai11/cryptopp.git
    fi
    pushd cryptopp
    git pull --prune
    git submodule update --init --recursive
    $GNU_MAKE deps
    $GNU_MAKE -kj 2
}

function download_scowl_for_hunspell {
    url='https://downloads.sourceforge.net/project/wordlist/speller/2017.01.22/'
    url+='hunspell-en_US-2017.01.22.zip?r=https%3A%2F%2Fsourceforge.net%2F'
    url+='projects%2Fwordlist%2Ffiles%2Fspeller%2F2017.01.22%2F&ts=1486860415'
    url+='&use_mirror=vorboss'
    wget "$url" -O hunspell-en_US-2017.01.22.zip
    unzip -o -d hunspell hunspell-en_US-2017.01.22.zip
    rm hunspell-en_US-2017.01.22.zip
}

build_boost &
build_gtest &
build_hunspell &
build_cryptopp &
wait
