#!/usr/bin/env bash

# Prerequisites:
# - GNU Bash (at least v3.1 for the '+=' string-concatenation operator).
# - Latest GCC ('gcc' and 'g++') available in PATH.
# - Environment variables:
#   - BOOST_DIR: Absolute or relative directory to Boost repo clone.
#   - GTEST_DIR: Absolute or relative directory to Google Test repo clone.
#   - HUNSPELL_DIR: Absolute or relative directory to Hunspell repo clone.
#   - CRYPTOPP_DIR: Absolute or relative directory to Crypto++ repo clone.
#   - OPENSSL_DIR: Absolute or relative directory to OpenSSL repo clone.
#   - GNU_MAKE: Executable name of GNU Make (at least v4.2.1).
#   - BAZEL: Executable name of Bazel. (Set to "true" for Makefile workaround.) 
#   - GIT: Executable name of Git (relatively modern version with submodules).
#   - AR: Executable name of GCC's 'ar' tool. (Unnecessary on macOS.)
#   - RANLIB: Executable name of GCC's 'ranlib' tool. (Unnecessary on macOS.)
#   - CLEAN_BUILD: (Optional) Clean up existing build artifacts before building.
#   - SKIP_COMPILER: (Optional) Only run code-generation steps for IDEs/linters.
export BOOST_DIR=${BOOST_DIR:-boost}
export GTEST_DIR=${GTEST_DIR:-googletest}
export HUNSPELL_DIR=${HUNSPELL_DIR:-hunspell}
export CRYPTOPP_DIR=${CRYPTOPP_DIR:-cryptopp}
export OPENSSL_DIR=${OPENSSL_DIR:-openssl}
export GNU_MAKE=${GNU_MAKE:-make}
export BAZEL=${BAZEL:-true}
export GIT=${GIT:-git}
if [[ $(uname) != "Darwin" ]]
then
    export AR=${AR:-gcc-ar}
    export RANLIB=${RANLIB:-gcc-ranlib}
fi

function build_boost {
    # The Travis Cache plugin creates the directories beforehand, so we can't
    # use [[ ! -d $dir ]] here
    if [[ ! -x $BOOST_DIR/bootstrap.sh ]]
    then
        $GIT clone --depth 1 --shallow-submodules --no-tags --jobs 4 \
             https://github.com/boostorg/boost.git $BOOST_DIR
        pushd $BOOST_DIR
    else
        pushd $BOOST_DIR
        if [[ -n "$CLEAN_BUILD" ]]
        then
            $GIT clean --force -Xd
            $GIT checkout --force --no-recurse-submodules master
        fi
        $GIT pull --prune --no-recurse-submodules --no-tags --depth=1
    fi
    $GIT submodule update --init --recursive --checkout --depth 1 --jobs 4
    ./bootstrap.sh --with-toolset=gcc
    ./b2 headers
    [[ -z "$SKIP_COMPILER" ]] || return
    ./b2 --layout=system toolset=gcc variant=release address-model=64 -j 2 \
         --with-system
}

function build_gtest {
    if [[ ! -f $GTEST_DIR/BUILD.bazel && ! -f $GTEST_DIR/WORKSPACE ]]
    then
        $GIT clone --depth 1 --shallow-submodules --no-tags --jobs 4 \
             https://github.com/google/googletest.git $GTEST_DIR
        pushd $GTEST_DIR
    else
        pushd $GTEST_DIR
        if [[ -n "$CLEAN_BUILD" ]]
        then
            $GIT clean --force -Xd
            $GIT checkout --force --no-recurse-submodules main
        fi
        $GIT pull --prune --no-recurse-submodules --no-tags --depth=1
    fi
    $GIT submodule update --init --recursive --checkout --depth 1 --jobs 4
    [[ -z "$SKIP_COMPILER" ]] || return
    if [[ $BAZEL != "true" ]]
    then
        system_name=$(uname -s)
        if [[ $system_name =~ ^MINGW ]]
        then
            compiler_override="--compiler=mingw-gcc"
        elif [[ $system_name =~ ^MSYS_ ]]
        then
            compiler_override="--compiler=msys-gcc"
        fi
        compiler_override+=" --cxxopt=-std=c++14"
        $BAZEL --batch build $compiler_override gtest gtest_main
    else
        git fetch --shallow-since=2019-06-12
        git checkout 6b8c138154~1 -- googletest/make
        pushd googletest/make
        $GNU_MAKE -kj 2
        popd
        [[ -d bazel-bin ]] || mkdir bazel-bin
        pushd bazel-bin
        ln -fs ../googletest/make/*.a .
    fi
}

function build_hunspell {
    if [[ ! -f $HUNSPELL_DIR/configure.ac ]]
    then
        $GIT clone --depth 1 --shallow-submodules --no-tags --jobs 4 \
             https://github.com/hunspell/hunspell.git $HUNSPELL_DIR
        pushd $HUNSPELL_DIR
    else
        pushd $HUNSPELL_DIR
        if [[ -n "$CLEAN_BUILD" ]]
        then
            $GIT clean --force -Xd
            rm -f config.cache
            $GIT checkout --force --no-recurse-submodules master
        fi
        $GIT pull --prune --no-recurse-submodules --no-tags --depth=1
    fi
    $GIT submodule update --init --recursive --checkout --depth 1 --jobs 4
    if [[ -z `command -v autopoint` &&
          `uname` == Linux && `lsb_release -s -i` == Ubuntu ]]
    then
        sudo apt install -y autopoint
    fi
    export LDFLAGS=-L/usr/local/opt/gettext/lib
    export CPPFLAGS=-I/usr/local/opt/gettext/include
    autoreconf -vfi
    ./configure --config-cache --disable-dependency-tracking
    [[ -z "$SKIP_COMPILER" ]] || return
    $GNU_MAKE -kj 2
}

function build_cryptopp {
    if [[ ! -f $CRYPTOPP_DIR/GNUmakefile ]]
    then
        $GIT clone --depth 1 --shallow-submodules --no-tags --jobs 4 \
             https://github.com/weidai11/cryptopp.git $CRYPTOPP_DIR
        pushd $CRYPTOPP_DIR
    else
        pushd $CRYPTOPP_DIR
        if [[ -n "$CLEAN_BUILD" ]]
        then
            $GIT clean --force -Xd
            $GIT checkout --force --no-recurse-submodules master
        fi
        $GIT pull --prune --no-recurse-submodules --no-tags --depth=1
    fi
    $GIT submodule update --init --recursive --checkout --depth 1 --jobs 4
    [[ -z "$SKIP_COMPILER" ]] || return
    $GNU_MAKE deps
    $GNU_MAKE -kj 3
}

function build_openssl {
    if [[ ! -f $OPENSSL_DIR/config ]]
    then
        $GIT clone --config core.eol=lf --config core.autocrlf=false --depth 1 \
             --shallow-submodules --no-tags --jobs 4 \
             https://github.com/openssl/openssl.git $OPENSSL_DIR
        pushd $OPENSSL_DIR
    else
        pushd $OPENSSL_DIR
        if [[ -n "$CLEAN_BUILD" ]]
        then
            $GIT config core.eol lf
            $GIT config core.autocrlf false
            $GIT clean --force -Xd
            $GIT checkout --force --no-recurse-submodules master
        fi
        $GIT pull --prune --no-recurse-submodules --no-tags --depth=1
    fi
    $GIT submodule update --init --recursive --checkout --depth 1 --jobs 4
    CC=gcc CXX=g++ ./config --prefix=$(pwd) no-async enable-makedepend
    $GNU_MAKE update -kj 3
    [[ -z "$SKIP_COMPILER" ]] || return
    $GNU_MAKE -kj 3
    # https://github.com/openssl/openssl/issues/14994#issuecomment-825872628
    $GNU_MAKE -kj 3
    $GNU_MAKE -kj 3
    [[ -d lib ]] || mkdir lib
    pushd lib
    ln -fs ../libssl.* ../libcrypto.* .
}

function download_scowl_for_hunspell {
    url='https://downloads.sourceforge.net/project/wordlist/speller/2017.01.22/'
    url+='hunspell-en_US-2017.01.22.zip?r=https%3A%2F%2Fsourceforge.net%2F'
    url+='projects%2Fwordlist%2Ffiles%2Fspeller%2F2017.01.22%2F&ts=1486860415'
    url+='&use_mirror=vorboss'
    wget "$url" -O hunspell-en_US-2017.01.22.zip
    unzip -o -d $HUNSPELL_DIR hunspell-en_US-2017.01.22.zip
    rm hunspell-en_US-2017.01.22.zip
}

set -xe
build_boost &
build_gtest &
build_hunspell &
build_cryptopp &
build_openssl &
[[ -n "$SKIP_COMPILER" ]] || download_scowl_for_hunspell &
wait
