VPATH = \
../challenge_1_convert_hex_to_base64 \
../challenge_2_fixed_xor

SRCS = \
test_break_single_byte_xor_cipher.cpp \
repeating_stringstream.cpp \
break_single_byte_xor_cipher.cpp \
xor_combine.cpp \
decode_hex.cpp \
encode_hex.cpp

test_break_single_byte_xor_cipher : $(SRCS:.cpp=.o)

include ../../common_settings.mk
