VPATH = ../../set_1_basics/challenge_1_convert_hex_to_base64

SRCS = \
test_pkcs7_pad.cpp \
pkcs7_pad.cpp

test_pkcs7_pad : $(SRCS:.cpp=.o)

include $(dir $(lastword $(MAKEFILE_LIST)))../../common_settings.mk
